// Hårdkodad fallback med kända stjärnspelare per nation.
// Används bara när football-data.org inte returnerar en trupp.
// Ersätts automatiskt så fort den officiella VM-truppen publiceras.

export type FallbackPosition = 'Goalkeeper' | 'Defender' | 'Midfielder' | 'Forward'

export interface FallbackPlayer {
  name: string
  position: FallbackPosition
  club?: string
  youthClub?: string       // Moderklubb
  marketValueM?: number    // Bedömt marknadsvärde i miljoner EUR
}

export const WC_FALLBACK_SQUADS: Record<string, FallbackPlayer[]> = {
  SWE: [
    { name: 'Robin Olsen', position: 'Goalkeeper', club: 'Aston Villa', youthClub: 'Malmö FF', marketValueM: 2 },
    { name: 'Kristoffer Nordfeldt', position: 'Goalkeeper', club: 'Hammarby', youthClub: 'Värmbols FC', marketValueM: 1 },
    { name: 'Victor Lindelöf', position: 'Defender', club: 'Aston Villa', youthClub: 'Västerås SK', marketValueM: 10 },
    { name: 'Gabriel Gudmundsson', position: 'Defender', club: 'Leeds United', youthClub: 'Helsingborgs IF', marketValueM: 15 },
    { name: 'Isak Hien', position: 'Defender', club: 'Atalanta', youthClub: 'Djurgårdens IF', marketValueM: 25 },
    { name: 'Emil Krafth', position: 'Defender', club: 'Newcastle United', youthClub: 'Östersunds FK', marketValueM: 3 },
    { name: 'Jens Cajuste', position: 'Midfielder', club: 'Ipswich Town', youthClub: 'Gerdskens BK', marketValueM: 9 },
    { name: 'Hjalmar Ekdal', position: 'Defender', club: 'Burnley', youthClub: 'Helsingborgs IF', marketValueM: 5 },
    { name: 'Anthony Elanga', position: 'Forward', club: 'Newcastle United', youthClub: 'Hammarby IF', marketValueM: 35 },
    { name: 'Dejan Kulusevski', position: 'Midfielder', club: 'Tottenham', youthClub: 'Brommapojkarna', marketValueM: 38 },
    { name: 'Alexander Isak', position: 'Forward', club: 'Liverpool', youthClub: 'AIK', marketValueM: 130 },
    { name: 'Viktor Gyökeres', position: 'Forward', club: 'Arsenal', youthClub: 'Brommapojkarna', marketValueM: 95 },
    { name: 'Lucas Bergvall', position: 'Midfielder', club: 'Tottenham', youthClub: 'Brommapojkarna', marketValueM: 50 },
    { name: 'Yasin Ayari', position: 'Midfielder', club: 'Brighton', youthClub: 'AIK', marketValueM: 22 },
    { name: 'Daniel Svensson', position: 'Defender', club: 'Borussia Dortmund', youthClub: 'IFK Norrköping', marketValueM: 14 },
  ],
  BRA: [
    { name: 'Alisson', position: 'Goalkeeper', club: 'Liverpool', marketValueM: 35 },
    { name: 'Ederson', position: 'Goalkeeper', club: 'Manchester City', marketValueM: 25 },
    { name: 'Marquinhos', position: 'Defender', club: 'Paris Saint-Germain', marketValueM: 45 },
    { name: 'Éder Militão', position: 'Defender', club: 'Real Madrid', marketValueM: 55 },
    { name: 'Gabriel Magalhães', position: 'Defender', club: 'Arsenal', marketValueM: 75 },
    { name: 'Danilo', position: 'Defender', club: 'Flamengo', marketValueM: 8 },
    { name: 'Casemiro', position: 'Midfielder', club: 'Manchester United', marketValueM: 18 },
    { name: 'Bruno Guimarães', position: 'Midfielder', club: 'Newcastle United', marketValueM: 75 },
    { name: 'Lucas Paquetá', position: 'Midfielder', club: 'West Ham', marketValueM: 45 },
    { name: 'Vinícius Júnior', position: 'Forward', club: 'Real Madrid', marketValueM: 180 },
    { name: 'Rodrygo', position: 'Forward', club: 'Real Madrid', marketValueM: 90 },
    { name: 'Raphinha', position: 'Forward', club: 'Barcelona', marketValueM: 90 },
    { name: 'Endrick', position: 'Forward', club: 'Real Madrid', marketValueM: 60 },
    { name: 'Estêvão', position: 'Forward', club: 'Chelsea', marketValueM: 70 },
  ],
  ARG: [
    { name: 'Emiliano Martínez', position: 'Goalkeeper', club: 'Aston Villa', marketValueM: 25 },
    { name: 'Gerónimo Rulli', position: 'Goalkeeper', club: 'Marseille', marketValueM: 8 },
    { name: 'Cristian Romero', position: 'Defender', club: 'Tottenham', marketValueM: 55 },
    { name: 'Lisandro Martínez', position: 'Defender', club: 'Manchester United', marketValueM: 45 },
    { name: 'Nicolás Otamendi', position: 'Defender', club: 'Benfica', marketValueM: 3 },
    { name: 'Nahuel Molina', position: 'Defender', club: 'Atlético Madrid', marketValueM: 28 },
    { name: 'Leandro Paredes', position: 'Midfielder', club: 'Roma', marketValueM: 8 },
    { name: 'Rodrigo De Paul', position: 'Midfielder', club: 'Atlético Madrid', marketValueM: 22 },
    { name: 'Enzo Fernández', position: 'Midfielder', club: 'Chelsea', marketValueM: 80 },
    { name: 'Alexis Mac Allister', position: 'Midfielder', club: 'Liverpool', marketValueM: 80 },
    { name: 'Lionel Messi', position: 'Forward', club: 'Inter Miami', marketValueM: 18 },
    { name: 'Lautaro Martínez', position: 'Forward', club: 'Inter', marketValueM: 100 },
    { name: 'Julián Álvarez', position: 'Forward', club: 'Atlético Madrid', marketValueM: 90 },
    { name: 'Ángel Di María', position: 'Forward', club: 'Benfica', marketValueM: 4 },
  ],
  FRA: [
    { name: 'Mike Maignan', position: 'Goalkeeper', club: 'Milan', marketValueM: 35 },
    { name: 'Brice Samba', position: 'Goalkeeper', club: 'Rennes', marketValueM: 8 },
    { name: 'Jules Koundé', position: 'Defender', club: 'Barcelona', marketValueM: 60 },
    { name: 'William Saliba', position: 'Defender', club: 'Arsenal', marketValueM: 80 },
    { name: 'Dayot Upamecano', position: 'Defender', club: 'Bayern Munich', marketValueM: 60 },
    { name: 'Theo Hernández', position: 'Defender', club: 'Al-Hilal', marketValueM: 30 },
    { name: 'Aurélien Tchouaméni', position: 'Midfielder', club: 'Real Madrid', marketValueM: 80 },
    { name: 'Eduardo Camavinga', position: 'Midfielder', club: 'Real Madrid', marketValueM: 70 },
    { name: 'Adrien Rabiot', position: 'Midfielder', club: 'Marseille', marketValueM: 18 },
    { name: 'Warren Zaïre-Emery', position: 'Midfielder', club: 'Paris Saint-Germain', marketValueM: 60 },
    { name: 'Kylian Mbappé', position: 'Forward', club: 'Real Madrid', marketValueM: 180 },
    { name: 'Ousmane Dembélé', position: 'Forward', club: 'Paris Saint-Germain', marketValueM: 90 },
    { name: 'Bradley Barcola', position: 'Forward', club: 'Paris Saint-Germain', marketValueM: 60 },
    { name: 'Michael Olise', position: 'Forward', club: 'Bayern Munich', marketValueM: 90 },
    { name: 'Désiré Doué', position: 'Forward', club: 'Paris Saint-Germain', marketValueM: 80 },
  ],
  ENG: [
    { name: 'Jordan Pickford', position: 'Goalkeeper', club: 'Everton', marketValueM: 18 },
    { name: 'Dean Henderson', position: 'Goalkeeper', club: 'Crystal Palace', marketValueM: 12 },
    { name: 'Kyle Walker', position: 'Defender', club: 'Burnley', marketValueM: 4 },
    { name: 'John Stones', position: 'Defender', club: 'Manchester City', marketValueM: 25 },
    { name: 'Marc Guéhi', position: 'Defender', club: 'Crystal Palace', marketValueM: 55 },
    { name: 'Levi Colwill', position: 'Defender', club: 'Chelsea', marketValueM: 50 },
    { name: 'Declan Rice', position: 'Midfielder', club: 'Arsenal', marketValueM: 110 },
    { name: 'Jude Bellingham', position: 'Midfielder', club: 'Real Madrid', marketValueM: 180 },
    { name: 'Cole Palmer', position: 'Midfielder', club: 'Chelsea', marketValueM: 130 },
    { name: 'Phil Foden', position: 'Midfielder', club: 'Manchester City', marketValueM: 120 },
    { name: 'Bukayo Saka', position: 'Forward', club: 'Arsenal', marketValueM: 130 },
    { name: 'Harry Kane', position: 'Forward', club: 'Bayern Munich', marketValueM: 80 },
    { name: 'Anthony Gordon', position: 'Forward', club: 'Newcastle United', marketValueM: 70 },
    { name: 'Morgan Rogers', position: 'Forward', club: 'Aston Villa', marketValueM: 50 },
  ],
  ESP: [
    { name: 'Unai Simón', position: 'Goalkeeper', club: 'Athletic Bilbao', marketValueM: 22 },
    { name: 'David Raya', position: 'Goalkeeper', club: 'Arsenal', marketValueM: 30 },
    { name: 'Dani Carvajal', position: 'Defender', club: 'Real Madrid', marketValueM: 18 },
    { name: 'Aymeric Laporte', position: 'Defender', club: 'Al-Nassr', marketValueM: 12 },
    { name: 'Robin Le Normand', position: 'Defender', club: 'Atlético Madrid', marketValueM: 35 },
    { name: 'Marc Cucurella', position: 'Defender', club: 'Chelsea', marketValueM: 35 },
    { name: 'Pedri', position: 'Midfielder', club: 'Barcelona', marketValueM: 130 },
    { name: 'Rodri', position: 'Midfielder', club: 'Manchester City', marketValueM: 130 },
    { name: 'Mikel Merino', position: 'Midfielder', club: 'Arsenal', marketValueM: 50 },
    { name: 'Fabián Ruiz', position: 'Midfielder', club: 'Paris Saint-Germain', marketValueM: 60 },
    { name: 'Lamine Yamal', position: 'Forward', club: 'Barcelona', marketValueM: 200 },
    { name: 'Nico Williams', position: 'Forward', club: 'Athletic Bilbao', marketValueM: 75 },
    { name: 'Álvaro Morata', position: 'Forward', club: 'Como', marketValueM: 14 },
    { name: 'Mikel Oyarzabal', position: 'Forward', club: 'Real Sociedad', marketValueM: 40 },
    { name: 'Dani Olmo', position: 'Forward', club: 'Barcelona', marketValueM: 55 },
  ],
  POR: [
    { name: 'Diogo Costa', position: 'Goalkeeper', club: 'Porto', marketValueM: 30 },
    { name: 'Rui Patrício', position: 'Goalkeeper', club: 'Al-Ain', marketValueM: 1 },
    { name: 'Rúben Dias', position: 'Defender', club: 'Manchester City', marketValueM: 70 },
    { name: 'Pepe', position: 'Defender', club: 'Porto', marketValueM: 1 },
    { name: 'João Cancelo', position: 'Defender', club: 'Al-Hilal', marketValueM: 14 },
    { name: 'Nuno Mendes', position: 'Defender', club: 'Paris Saint-Germain', marketValueM: 75 },
    { name: 'Rúben Neves', position: 'Midfielder', club: 'Al-Hilal', marketValueM: 22 },
    { name: 'Bernardo Silva', position: 'Midfielder', club: 'Manchester City', marketValueM: 60 },
    { name: 'Bruno Fernandes', position: 'Midfielder', club: 'Manchester United', marketValueM: 60 },
    { name: 'Vitinha', position: 'Midfielder', club: 'Paris Saint-Germain', marketValueM: 90 },
    { name: 'Cristiano Ronaldo', position: 'Forward', club: 'Al-Nassr', marketValueM: 12 },
    { name: 'Rafael Leão', position: 'Forward', club: 'Milan', marketValueM: 75 },
    { name: 'João Félix', position: 'Forward', club: 'Chelsea', marketValueM: 30 },
    { name: 'Gonçalo Ramos', position: 'Forward', club: 'Paris Saint-Germain', marketValueM: 45 },
  ],
  GER: [
    { name: 'Manuel Neuer', position: 'Goalkeeper', club: 'Bayern Munich', marketValueM: 4 },
    { name: 'Marc-André ter Stegen', position: 'Goalkeeper', club: 'Barcelona', marketValueM: 22 },
    { name: 'Antonio Rüdiger', position: 'Defender', club: 'Real Madrid', marketValueM: 28 },
    { name: 'Jonathan Tah', position: 'Defender', club: 'Bayern Munich', marketValueM: 50 },
    { name: 'Joshua Kimmich', position: 'Defender', club: 'Bayern Munich', marketValueM: 45 },
    { name: 'David Raum', position: 'Defender', club: 'RB Leipzig', marketValueM: 35 },
    { name: 'Toni Kroos', position: 'Midfielder', club: 'Real Madrid', marketValueM: 1 },
    { name: 'İlkay Gündoğan', position: 'Midfielder', club: 'Galatasaray', marketValueM: 5 },
    { name: 'Jamal Musiala', position: 'Midfielder', club: 'Bayern Munich', marketValueM: 140 },
    { name: 'Florian Wirtz', position: 'Midfielder', club: 'Liverpool', marketValueM: 140 },
    { name: 'Leroy Sané', position: 'Forward', club: 'Galatasaray', marketValueM: 28 },
    { name: 'Kai Havertz', position: 'Forward', club: 'Arsenal', marketValueM: 65 },
    { name: 'Niclas Füllkrug', position: 'Forward', club: 'West Ham', marketValueM: 14 },
    { name: 'Karim Adeyemi', position: 'Forward', club: 'Borussia Dortmund', marketValueM: 35 },
  ],
  NED: [
    { name: 'Bart Verbruggen', position: 'Goalkeeper', club: 'Brighton', marketValueM: 30 },
    { name: 'Justin Bijlow', position: 'Goalkeeper', club: 'Feyenoord', marketValueM: 7 },
    { name: 'Virgil van Dijk', position: 'Defender', club: 'Liverpool', marketValueM: 22 },
    { name: 'Matthijs de Ligt', position: 'Defender', club: 'Manchester United', marketValueM: 40 },
    { name: 'Denzel Dumfries', position: 'Defender', club: 'Inter', marketValueM: 25 },
    { name: 'Nathan Aké', position: 'Defender', club: 'Manchester City', marketValueM: 28 },
    { name: 'Frenkie de Jong', position: 'Midfielder', club: 'Barcelona', marketValueM: 45 },
    { name: 'Tijjani Reijnders', position: 'Midfielder', club: 'Manchester City', marketValueM: 80 },
    { name: 'Xavi Simons', position: 'Midfielder', club: 'Tottenham', marketValueM: 70 },
    { name: 'Cody Gakpo', position: 'Forward', club: 'Liverpool', marketValueM: 65 },
    { name: 'Memphis Depay', position: 'Forward', club: 'Corinthians', marketValueM: 5 },
    { name: 'Donyell Malen', position: 'Forward', club: 'Aston Villa', marketValueM: 18 },
    { name: 'Brian Brobbey', position: 'Forward', club: 'Sunderland', marketValueM: 14 },
  ],
  ITA: [
    { name: 'Gianluigi Donnarumma', position: 'Goalkeeper', club: 'Manchester City', marketValueM: 50 },
    { name: 'Guglielmo Vicario', position: 'Goalkeeper', club: 'Tottenham', marketValueM: 30 },
    { name: 'Alessandro Bastoni', position: 'Defender', club: 'Inter', marketValueM: 70 },
    { name: 'Federico Dimarco', position: 'Defender', club: 'Inter', marketValueM: 40 },
    { name: 'Giovanni Di Lorenzo', position: 'Defender', club: 'Napoli', marketValueM: 22 },
    { name: 'Riccardo Calafiori', position: 'Defender', club: 'Arsenal', marketValueM: 45 },
    { name: 'Nicolò Barella', position: 'Midfielder', club: 'Inter', marketValueM: 70 },
    { name: 'Sandro Tonali', position: 'Midfielder', club: 'Newcastle United', marketValueM: 65 },
    { name: 'Davide Frattesi', position: 'Midfielder', club: 'Roma', marketValueM: 35 },
    { name: 'Federico Chiesa', position: 'Forward', club: 'Liverpool', marketValueM: 22 },
    { name: 'Mateo Retegui', position: 'Forward', club: 'Al-Qadsiah', marketValueM: 35 },
    { name: 'Moise Kean', position: 'Forward', club: 'Fiorentina', marketValueM: 40 },
  ],
  CRO: [
    { name: 'Dominik Livaković', position: 'Goalkeeper', club: 'Girona', marketValueM: 1 },
    { name: 'Joško Gvardiol', position: 'Defender', club: 'Manchester City', marketValueM: 19 },
    { name: 'Joško Šutalo', position: 'Defender', club: 'Ajax', marketValueM: 8 },
    { name: 'Borna Sosa', position: 'Defender', club: 'Ajax', marketValueM: 8 },
    { name: 'Luka Modrić', position: 'Midfielder', club: 'Milan', marketValueM: 22 },
    { name: 'Mateo Kovačić', position: 'Midfielder', club: 'Manchester City', marketValueM: 22 },
    { name: 'Marcelo Brozović', position: 'Midfielder', club: 'Al-Nassr', marketValueM: 4 },
    { name: 'Andrej Kramarić', position: 'Forward', club: 'Hoffenheim', marketValueM: 10 },
    { name: 'Bruno Petković', position: 'Forward', club: 'Dinamo Zagreb', marketValueM: 3 },
    { name: 'Martin Baturina', position: 'Midfielder', club: 'Como', marketValueM: 9 },
  ],
  BEL: [
    { name: 'Thibaut Courtois', position: 'Goalkeeper', club: 'Real Madrid', marketValueM: 11 },
    { name: 'Koen Casteels', position: 'Goalkeeper', club: 'Al-Qadsiah', marketValueM: 2 },
    { name: 'Jan Vertonghen', position: 'Defender', club: 'Anderlecht', marketValueM: 2 },
    { name: 'Wout Faes', position: 'Defender', club: 'Leicester City', marketValueM: 8 },
    { name: 'Timothy Castagne', position: 'Defender', club: 'Fulham', marketValueM: 8 },
    { name: 'Kevin De Bruyne', position: 'Midfielder', club: 'Napoli', marketValueM: 22 },
    { name: 'Youri Tielemans', position: 'Midfielder', club: 'Aston Villa', marketValueM: 22 },
    { name: 'Charles De Ketelaere', position: 'Midfielder', club: 'Atalanta', marketValueM: 22 },
    { name: 'Romelu Lukaku', position: 'Forward', club: 'Napoli', marketValueM: 25 },
    { name: 'Jérémy Doku', position: 'Forward', club: 'Manchester City', marketValueM: 25 },
    { name: 'Leandro Trossard', position: 'Forward', club: 'Arsenal', marketValueM: 25 },
  ],
  SUI: [
    { name: 'Yann Sommer', position: 'Goalkeeper', club: 'Inter', marketValueM: 11 },
    { name: 'Manuel Akanji', position: 'Defender', club: 'Manchester City', marketValueM: 19 },
    { name: 'Ricardo Rodríguez', position: 'Defender', club: 'Real Betis', marketValueM: 8 },
    { name: 'Granit Xhaka', position: 'Midfielder', club: 'Sunderland', marketValueM: 9 },
    { name: 'Remo Freuler', position: 'Midfielder', club: 'Bologna', marketValueM: 9 },
    { name: 'Xherdan Shaqiri', position: 'Midfielder', club: 'Basel', marketValueM: 3 },
    { name: 'Breel Embolo', position: 'Forward', club: 'Monaco', marketValueM: 10 },
    { name: 'Dan Ndoye', position: 'Forward', club: 'Bologna', marketValueM: 10 },
  ],
  DEN: [
    { name: 'Kasper Schmeichel', position: 'Goalkeeper', club: 'Celtic', marketValueM: 4 },
    { name: 'Andreas Christensen', position: 'Defender', club: 'Barcelona', marketValueM: 19 },
    { name: 'Joachim Andersen', position: 'Defender', club: 'Fulham', marketValueM: 8 },
    { name: 'Joakim Mæhle', position: 'Defender', club: 'Wolfsburg', marketValueM: 8 },
    { name: 'Pierre-Emile Højbjerg', position: 'Midfielder', club: 'Marseille', marketValueM: 9 },
    { name: 'Christian Eriksen', position: 'Midfielder', club: 'Manchester United', marketValueM: 22 },
    { name: 'Mikkel Damsgaard', position: 'Midfielder', club: 'Brentford', marketValueM: 9 },
    { name: 'Rasmus Højlund', position: 'Forward', club: 'Napoli', marketValueM: 25 },
    { name: 'Jonas Wind', position: 'Forward', club: 'Wolfsburg', marketValueM: 10 },
  ],
  POL: [
    { name: 'Wojciech Szczęsny', position: 'Goalkeeper', club: 'Barcelona', marketValueM: 11 },
    { name: 'Jan Bednarek', position: 'Defender', club: 'Porto', marketValueM: 8 },
    { name: 'Matty Cash', position: 'Defender', club: 'Aston Villa', marketValueM: 19 },
    { name: 'Sebastian Szymański', position: 'Midfielder', club: 'Fenerbahçe', marketValueM: 9 },
    { name: 'Piotr Zieliński', position: 'Midfielder', club: 'Inter', marketValueM: 22 },
    { name: 'Nicola Zalewski', position: 'Midfielder', club: 'Atalanta', marketValueM: 22 },
    { name: 'Robert Lewandowski', position: 'Forward', club: 'Barcelona', marketValueM: 25 },
    { name: 'Karol Świderski', position: 'Forward', club: 'Hellas Verona', marketValueM: 10 },
  ],
  AUT: [
    { name: 'Patrick Pentz', position: 'Goalkeeper', club: 'Brøndby', marketValueM: 1 },
    { name: 'David Alaba', position: 'Defender', club: 'Real Madrid', marketValueM: 19 },
    { name: 'Kevin Danso', position: 'Defender', club: 'Wolverhampton', marketValueM: 8 },
    { name: 'Konrad Laimer', position: 'Midfielder', club: 'Bayern Munich', marketValueM: 22 },
    { name: 'Marcel Sabitzer', position: 'Midfielder', club: 'Borussia Dortmund', marketValueM: 22 },
    { name: 'Christoph Baumgartner', position: 'Midfielder', club: 'RB Leipzig', marketValueM: 22 },
    { name: 'Marko Arnautović', position: 'Forward', club: 'Inter', marketValueM: 25 },
  ],
  TUR: [
    { name: 'Altay Bayındır', position: 'Goalkeeper', club: 'Manchester United', marketValueM: 11 },
    { name: 'Mert Günok', position: 'Goalkeeper', club: 'Beşiktaş', marketValueM: 4 },
    { name: 'Merih Demiral', position: 'Defender', club: 'Al-Ahli', marketValueM: 3 },
    { name: 'Çağlar Söyüncü', position: 'Defender', club: 'Fenerbahçe', marketValueM: 8 },
    { name: 'Ferdi Kadıoğlu', position: 'Defender', club: 'Brighton', marketValueM: 19 },
    { name: 'Hakan Çalhanoğlu', position: 'Midfielder', club: 'Inter', marketValueM: 22 },
    { name: 'Arda Güler', position: 'Midfielder', club: 'Real Madrid', marketValueM: 22 },
    { name: 'Kenan Yıldız', position: 'Forward', club: 'Juventus', marketValueM: 25 },
    { name: 'Kerem Aktürkoğlu', position: 'Forward', club: 'Benfica', marketValueM: 10 },
  ],
  CZE: [
    { name: 'Jindřich Staněk', position: 'Goalkeeper', club: 'Slavia Praha', marketValueM: 1 },
    { name: 'Tomáš Vlček', position: 'Defender', club: 'Slavia Praha', marketValueM: 2 },
    { name: 'Tomáš Souček', position: 'Midfielder', club: 'West Ham', marketValueM: 9 },
    { name: 'Lukáš Provod', position: 'Midfielder', club: 'Slavia Praha', marketValueM: 3 },
    { name: 'Adam Hložek', position: 'Forward', club: 'Hoffenheim', marketValueM: 10 },
    { name: 'Patrik Schick', position: 'Forward', club: 'Bayer Leverkusen', marketValueM: 25 },
  ],
  NOR: [
    { name: 'Ørjan Nyland', position: 'Goalkeeper', club: 'Sevilla', marketValueM: 1 },
    { name: 'Kristoffer Ajer', position: 'Defender', club: 'Brentford', marketValueM: 8 },
    { name: 'Leo Skiri Østigård', position: 'Defender', club: 'Rennes', marketValueM: 8 },
    { name: 'Sander Berge', position: 'Midfielder', club: 'Fulham', marketValueM: 9 },
    { name: 'Martin Ødegaard', position: 'Midfielder', club: 'Arsenal', marketValueM: 22 },
    { name: 'Oscar Bobb', position: 'Forward', club: 'Manchester City', marketValueM: 25 },
    { name: 'Erling Haaland', position: 'Forward', club: 'Manchester City', marketValueM: 25 },
    { name: 'Antonio Nusa', position: 'Forward', club: 'RB Leipzig', marketValueM: 25 },
    { name: 'Alexander Sørloth', position: 'Forward', club: 'Atlético Madrid', marketValueM: 25 },
  ],
  HUN: [
    { name: 'Dénes Dibusz', position: 'Goalkeeper', club: 'Ferencváros', marketValueM: 1 },
    { name: 'Willi Orbán', position: 'Defender', club: 'RB Leipzig', marketValueM: 19 },
    { name: 'Attila Szalai', position: 'Defender', club: 'Hoffenheim', marketValueM: 8 },
    { name: 'Dominik Szoboszlai', position: 'Midfielder', club: 'Liverpool', marketValueM: 22 },
    { name: 'András Schäfer', position: 'Midfielder', club: 'Union Berlin', marketValueM: 3 },
    { name: 'Roland Sallai', position: 'Forward', club: 'Galatasaray', marketValueM: 10 },
    { name: 'Barnabás Varga', position: 'Forward', club: 'Ferencváros', marketValueM: 3 },
  ],
  SCO: [
    { name: 'Angus Gunn', position: 'Goalkeeper', club: 'Norwich City', marketValueM: 1 },
    { name: 'Andy Robertson', position: 'Defender', club: 'Liverpool', marketValueM: 19 },
    { name: 'Kieran Tierney', position: 'Defender', club: 'Celtic', marketValueM: 8 },
    { name: 'Scott McTominay', position: 'Midfielder', club: 'Napoli', marketValueM: 22 },
    { name: 'John McGinn', position: 'Midfielder', club: 'Aston Villa', marketValueM: 22 },
    { name: 'Billy Gilmour', position: 'Midfielder', club: 'Napoli', marketValueM: 22 },
    { name: 'Che Adams', position: 'Forward', club: 'Torino', marketValueM: 3 },
    { name: 'Lyndon Dykes', position: 'Forward', club: 'Birmingham City', marketValueM: 3 },
  ],
  WAL: [
    { name: 'Karl Darlow', position: 'Goalkeeper', club: 'Leeds United', marketValueM: 4 },
    { name: 'Ben Davies', position: 'Defender', club: 'Tottenham', marketValueM: 19 },
    { name: 'Joe Rodon', position: 'Defender', club: 'Leeds United', marketValueM: 8 },
    { name: 'Aaron Ramsey', position: 'Midfielder', club: 'Pumas UNAM', marketValueM: 3 },
    { name: 'Harry Wilson', position: 'Midfielder', club: 'Fulham', marketValueM: 9 },
    { name: 'Brennan Johnson', position: 'Forward', club: 'Tottenham', marketValueM: 25 },
    { name: 'Daniel James', position: 'Forward', club: 'Leeds United', marketValueM: 10 },
    { name: 'Kieffer Moore', position: 'Forward', club: 'Sheffield United', marketValueM: 10 },
  ],
  IRN: [
    { name: 'Alireza Beiranvand', position: 'Goalkeeper', club: 'Persepolis', marketValueM: 1 },
    { name: 'Sadegh Moharrami', position: 'Defender', club: 'Dinamo Zagreb', marketValueM: 2 },
    { name: 'Shojae Khalilzadeh', position: 'Defender', club: 'Al-Wahda', marketValueM: 3 },
    { name: 'Saeid Ezatolahi', position: 'Midfielder', club: 'Al-Akhdoud', marketValueM: 4 },
    { name: 'Alireza Jahanbakhsh', position: 'Midfielder', club: 'Heerenveen', marketValueM: 3 },
    { name: 'Mehdi Taremi', position: 'Forward', club: 'Inter', marketValueM: 25 },
    { name: 'Sardar Azmoun', position: 'Forward', club: 'Shabab Al-Ahli', marketValueM: 4 },
  ],
  KOR: [
    { name: 'Jo Hyeon-woo', position: 'Goalkeeper', club: 'Ulsan HD', marketValueM: 1 },
    { name: 'Kim Min-jae', position: 'Defender', club: 'Bayern Munich', marketValueM: 19 },
    { name: 'Kim Young-gwon', position: 'Defender', club: 'Ulsan HD', marketValueM: 2 },
    { name: 'Lee Jae-sung', position: 'Midfielder', club: 'Mainz', marketValueM: 9 },
    { name: 'Hwang In-beom', position: 'Midfielder', club: 'Feyenoord', marketValueM: 9 },
    { name: 'Lee Kang-in', position: 'Midfielder', club: 'Paris Saint-Germain', marketValueM: 22 },
    { name: 'Son Heung-min', position: 'Forward', club: 'LAFC', marketValueM: 3 },
    { name: 'Hwang Hee-chan', position: 'Forward', club: 'Wolverhampton', marketValueM: 10 },
    { name: 'Cho Gue-sung', position: 'Forward', club: 'Mainz', marketValueM: 10 },
  ],
  JPN: [
    { name: 'Zion Suzuki', position: 'Goalkeeper', club: 'Parma', marketValueM: 1 },
    { name: 'Ko Itakura', position: 'Defender', club: 'Ajax', marketValueM: 8 },
    { name: 'Takehiro Tomiyasu', position: 'Defender', club: 'Arsenal', marketValueM: 19 },
    { name: 'Hiroki Itō', position: 'Defender', club: 'Bayern Munich', marketValueM: 19 },
    { name: 'Wataru Endō', position: 'Midfielder', club: 'Liverpool', marketValueM: 22 },
    { name: 'Hidemasa Morita', position: 'Midfielder', club: 'Sporting CP', marketValueM: 9 },
    { name: 'Takefusa Kubo', position: 'Forward', club: 'Real Sociedad', marketValueM: 10 },
    { name: 'Daichi Kamada', position: 'Midfielder', club: 'Crystal Palace', marketValueM: 9 },
    { name: 'Kaoru Mitoma', position: 'Forward', club: 'Brighton', marketValueM: 25 },
    { name: 'Takumi Minamino', position: 'Forward', club: 'Monaco', marketValueM: 10 },
    { name: 'Ayase Ueda', position: 'Forward', club: 'Feyenoord', marketValueM: 10 },
  ],
  AUS: [
    { name: 'Mathew Ryan', position: 'Goalkeeper', club: 'Roma', marketValueM: 11 },
    { name: 'Harry Souttar', position: 'Defender', club: 'Sheffield United', marketValueM: 8 },
    { name: 'Cameron Burgess', position: 'Defender', club: 'Ipswich Town', marketValueM: 8 },
    { name: 'Aiden O’Neill', position: 'Midfielder', club: 'Standard Liège', marketValueM: 3 },
    { name: 'Ajdin Hrustic', position: 'Midfielder', club: 'Hellas Verona', marketValueM: 9 },
    { name: 'Riley McGree', position: 'Midfielder', club: 'Middlesbrough', marketValueM: 3 },
    { name: 'Mathew Leckie', position: 'Forward', club: 'Melbourne City', marketValueM: 3 },
    { name: 'Mitchell Duke', position: 'Forward', club: 'Machida Zelvia', marketValueM: 3 },
  ],
  KSA: [
    { name: 'Mohammed Al-Owais', position: 'Goalkeeper', club: 'Al-Hilal', marketValueM: 2 },
    { name: 'Ali Al-Bulaihi', position: 'Defender', club: 'Al-Hilal', marketValueM: 3 },
    { name: 'Yasser Al-Shahrani', position: 'Defender', club: 'Al-Hilal', marketValueM: 3 },
    { name: 'Salem Al-Dawsari', position: 'Forward', club: 'Al-Hilal', marketValueM: 4 },
    { name: 'Saleh Al-Shehri', position: 'Forward', club: 'Al-Ittihad', marketValueM: 4 },
    { name: 'Firas Al-Buraikan', position: 'Forward', club: 'Al-Ahli', marketValueM: 4 },
  ],
  IRQ: [
    { name: 'Jalal Hassan', position: 'Goalkeeper', club: 'Al-Quwa Al-Jawiya', marketValueM: 1 },
    { name: 'Rebin Sulaka', position: 'Defender', club: 'Al-Najma', marketValueM: 2 },
    { name: 'Ali Al-Hamadi', position: 'Forward', club: 'Ipswich Town', marketValueM: 10 },
    { name: 'Aymen Hussein', position: 'Forward', club: 'Al-Najmah', marketValueM: 3 },
    { name: 'Bashar Resan', position: 'Midfielder', club: 'Persepolis', marketValueM: 3 },
  ],
  UZB: [
    { name: 'Utkir Yusupov', position: 'Goalkeeper', club: 'Pakhtakor', marketValueM: 1 },
    { name: 'Abdukodir Khusanov', position: 'Defender', club: 'Manchester City', marketValueM: 19 },
    { name: 'Eldor Shomurodov', position: 'Forward', club: 'Roma', marketValueM: 25 },
    { name: 'Jaloliddin Masharipov', position: 'Midfielder', club: 'Pakhtakor', marketValueM: 3 },
    { name: 'Khojimat Erkinov', position: 'Midfielder', club: 'Pakhtakor', marketValueM: 3 },
  ],
  JOR: [
    { name: 'Yazeed Abulaila', position: 'Goalkeeper', club: 'Al-Wehdat', marketValueM: 2 },
    { name: 'Salem Al-Ajalin', position: 'Defender', club: 'Al-Ramtha', marketValueM: 2 },
    { name: 'Mousa Al-Tamari', position: 'Forward', club: 'Rennes', marketValueM: 10 },
    { name: 'Yazan Al-Naimat', position: 'Forward', club: 'Al-Ahli', marketValueM: 4 },
    { name: 'Noor Al-Rawabdeh', position: 'Midfielder', club: 'Al-Faisaly', marketValueM: 4 },
  ],
  QAT: [
    { name: 'Meshaal Barsham', position: 'Goalkeeper', club: 'Al-Sadd', marketValueM: 2 },
    { name: 'Bassam Al-Rawi', position: 'Defender', club: 'Al-Duhail', marketValueM: 3 },
    { name: 'Akram Afif', position: 'Forward', club: 'Al-Sadd', marketValueM: 4 },
    { name: 'Almoez Ali', position: 'Forward', club: 'Al-Duhail', marketValueM: 4 },
    { name: 'Hassan Al-Haydos', position: 'Midfielder', club: 'Al-Sadd', marketValueM: 4 },
  ],
  USA: [
    { name: 'Matt Turner', position: 'Goalkeeper', club: 'Crystal Palace', marketValueM: 4 },
    { name: 'Patrick Schulte', position: 'Goalkeeper', club: 'Columbus Crew', marketValueM: 1 },
    { name: 'Sergiño Dest', position: 'Defender', club: 'PSV Eindhoven', marketValueM: 8 },
    { name: 'Antonee Robinson', position: 'Defender', club: 'Fulham', marketValueM: 8 },
    { name: 'Chris Richards', position: 'Defender', club: 'Crystal Palace', marketValueM: 8 },
    { name: 'Tim Ream', position: 'Defender', club: 'Charlotte FC', marketValueM: 2 },
    { name: 'Tyler Adams', position: 'Midfielder', club: 'Bournemouth', marketValueM: 9 },
    { name: 'Weston McKennie', position: 'Midfielder', club: 'Juventus', marketValueM: 22 },
    { name: 'Yunus Musah', position: 'Midfielder', club: 'Milan', marketValueM: 22 },
    { name: 'Christian Pulisic', position: 'Forward', club: 'Milan', marketValueM: 25 },
    { name: 'Timothy Weah', position: 'Forward', club: 'Juventus', marketValueM: 25 },
    { name: 'Folarin Balogun', position: 'Forward', club: 'Monaco', marketValueM: 10 },
    { name: 'Ricardo Pepi', position: 'Forward', club: 'PSV Eindhoven', marketValueM: 10 },
    { name: 'Gio Reyna', position: 'Forward', club: 'Borussia Dortmund', marketValueM: 25 },
  ],
  MEX: [
    { name: 'Guillermo Ochoa', position: 'Goalkeeper', club: 'AVS', marketValueM: 1 },
    { name: 'Luis Malagón', position: 'Goalkeeper', club: 'Club América', marketValueM: 1 },
    { name: 'Jesús Gallardo', position: 'Defender', club: 'Toluca', marketValueM: 2 },
    { name: 'César Montes', position: 'Defender', club: 'Lokomotiv Moscow', marketValueM: 2 },
    { name: 'Edson Álvarez', position: 'Midfielder', club: 'West Ham', marketValueM: 9 },
    { name: 'Luis Chávez', position: 'Midfielder', club: 'Dynamo Moscow', marketValueM: 3 },
    { name: 'Orbelín Pineda', position: 'Midfielder', club: 'AEK Athens', marketValueM: 3 },
    { name: 'Hirving Lozano', position: 'Forward', club: 'San Diego FC', marketValueM: 3 },
    { name: 'Santiago Giménez', position: 'Forward', club: 'Milan', marketValueM: 25 },
    { name: 'Raúl Jiménez', position: 'Forward', club: 'Fulham', marketValueM: 10 },
    { name: 'Julián Quiñones', position: 'Forward', club: 'Al-Qadsiah', marketValueM: 4 },
  ],
  CAN: [
    { name: 'Maxime Crépeau', position: 'Goalkeeper', club: 'Portland Timbers', marketValueM: 1 },
    { name: 'Dayne St. Clair', position: 'Goalkeeper', club: 'Minnesota United', marketValueM: 1 },
    { name: 'Alistair Johnston', position: 'Defender', club: 'Celtic', marketValueM: 8 },
    { name: 'Moïse Bombito', position: 'Defender', club: 'Nice', marketValueM: 8 },
    { name: 'Stephen Eustáquio', position: 'Midfielder', club: 'Porto', marketValueM: 9 },
    { name: 'Ismaël Koné', position: 'Midfielder', club: 'Sassuolo', marketValueM: 3 },
    { name: 'Alphonso Davies', position: 'Defender', club: 'Bayern Munich', marketValueM: 19 },
    { name: 'Tajon Buchanan', position: 'Forward', club: 'Villarreal', marketValueM: 10 },
    { name: 'Jonathan David', position: 'Forward', club: 'Juventus', marketValueM: 25 },
    { name: 'Cyle Larin', position: 'Forward', club: 'Mallorca', marketValueM: 3 },
  ],
  CRC: [
    { name: 'Keylor Navas', position: 'Goalkeeper', club: 'Newell’s Old Boys', marketValueM: 1 },
    { name: 'Patrick Sequeira', position: 'Goalkeeper', club: 'Casa Pia', marketValueM: 1 },
    { name: 'Francisco Calvo', position: 'Defender', club: 'Configuración', marketValueM: 2 },
    { name: 'Joel Campbell', position: 'Forward', club: 'Saprissa', marketValueM: 3 },
    { name: 'Manfred Ugalde', position: 'Forward', club: 'Spartak Moscow', marketValueM: 3 },
  ],
  HON: [
    { name: 'Edrick Menjívar', position: 'Goalkeeper', club: 'Olimpia', marketValueM: 1 },
    { name: 'Marcelo Pereira', position: 'Defender', club: 'Olimpia', marketValueM: 2 },
    { name: 'Andy Najar', position: 'Defender', club: 'Inter Miami', marketValueM: 2 },
    { name: 'Anthony Lozano', position: 'Forward', club: 'Cádiz', marketValueM: 3 },
    { name: 'Romell Quioto', position: 'Forward', club: 'CF Montréal', marketValueM: 3 },
  ],
  PAN: [
    { name: 'Orlando Mosquera', position: 'Goalkeeper', club: 'Universitario', marketValueM: 1 },
    { name: 'Michael Murillo', position: 'Defender', club: 'Marseille', marketValueM: 8 },
    { name: 'Aníbal Godoy', position: 'Midfielder', club: 'San Jose Earthquakes', marketValueM: 3 },
    { name: 'Adalberto Carrasquilla', position: 'Midfielder', club: 'Pumas UNAM', marketValueM: 3 },
    { name: 'José Fajardo', position: 'Forward', club: 'Independiente del Valle', marketValueM: 3 },
  ],
  HAI: [
    { name: 'Josué Duverger', position: 'Goalkeeper', club: 'Cavalry', marketValueM: 1 },
    { name: 'Carlens Arcus', position: 'Defender', club: 'Auxerre', marketValueM: 2 },
    { name: 'Frantzdy Pierrot', position: 'Forward', club: 'Mladá Boleslav', marketValueM: 3 },
    { name: 'Duckens Nazon', position: 'Forward', club: 'Caen', marketValueM: 3 },
  ],
  CUW: [
    { name: 'Eloy Room', position: 'Goalkeeper', club: 'Columbus Crew', marketValueM: 1 },
    { name: 'Cuco Martina', position: 'Defender', club: 'Arouca', marketValueM: 2 },
    { name: 'Leandro Bacuna', position: 'Midfielder', club: 'Birmingham City', marketValueM: 3 },
    { name: 'Tahith Chong', position: 'Forward', club: 'Sheffield United', marketValueM: 10 },
    { name: 'Juninho Bacuna', position: 'Midfielder', club: 'Birmingham City', marketValueM: 3 },
  ],
  COL: [
    { name: 'Camilo Vargas', position: 'Goalkeeper', club: 'Atlas', marketValueM: 1 },
    { name: 'Davinson Sánchez', position: 'Defender', club: 'Galatasaray', marketValueM: 8 },
    { name: 'Daniel Muñoz', position: 'Defender', club: 'Crystal Palace', marketValueM: 8 },
    { name: 'Jhon Lucumí', position: 'Defender', club: 'Bologna', marketValueM: 8 },
    { name: 'James Rodríguez', position: 'Midfielder', club: 'Club León', marketValueM: 3 },
    { name: 'Jefferson Lerma', position: 'Midfielder', club: 'Crystal Palace', marketValueM: 9 },
    { name: 'Richard Ríos', position: 'Midfielder', club: 'Palmeiras', marketValueM: 3 },
    { name: 'Luis Díaz', position: 'Forward', club: 'Bayern Munich', marketValueM: 25 },
    { name: 'Jhon Durán', position: 'Forward', club: 'Fenerbahçe', marketValueM: 10 },
    { name: 'Rafael Santos Borré', position: 'Forward', club: 'Internacional', marketValueM: 3 },
  ],
  URU: [
    { name: 'Sergio Rochet', position: 'Goalkeeper', club: 'Internacional', marketValueM: 1 },
    { name: 'Ronald Araújo', position: 'Defender', club: 'Barcelona', marketValueM: 19 },
    { name: 'José María Giménez', position: 'Defender', club: 'Atlético Madrid', marketValueM: 19 },
    { name: 'Mathías Olivera', position: 'Defender', club: 'Napoli', marketValueM: 19 },
    { name: 'Federico Valverde', position: 'Midfielder', club: 'Real Madrid', marketValueM: 22 },
    { name: 'Manuel Ugarte', position: 'Midfielder', club: 'Manchester United', marketValueM: 22 },
    { name: 'Nicolás de la Cruz', position: 'Midfielder', club: 'Flamengo', marketValueM: 3 },
    { name: 'Darwin Núñez', position: 'Forward', club: 'Al-Hilal', marketValueM: 4 },
    { name: 'Maximiliano Araújo', position: 'Forward', club: 'Sporting CP', marketValueM: 10 },
    { name: 'Facundo Pellistri', position: 'Forward', club: 'Panathinaikos', marketValueM: 3 },
  ],
  ECU: [
    { name: 'Hernán Galíndez', position: 'Goalkeeper', club: 'Huracán', marketValueM: 1 },
    { name: 'Pervis Estupiñán', position: 'Defender', club: 'Milan', marketValueM: 19 },
    { name: 'Piero Hincapié', position: 'Defender', club: 'Bayer Leverkusen', marketValueM: 19 },
    { name: 'Willian Pacho', position: 'Defender', club: 'Paris Saint-Germain', marketValueM: 19 },
    { name: 'Moisés Caicedo', position: 'Midfielder', club: 'Chelsea', marketValueM: 22 },
    { name: 'Kendry Páez', position: 'Midfielder', club: 'Strasbourg', marketValueM: 9 },
    { name: 'Enner Valencia', position: 'Forward', club: 'Internacional', marketValueM: 3 },
    { name: 'Gonzalo Plata', position: 'Forward', club: 'Flamengo', marketValueM: 3 },
  ],
  PAR: [
    { name: 'Roberto Fernández', position: 'Goalkeeper', club: 'Cerro Porteño', marketValueM: 1 },
    { name: 'Gustavo Gómez', position: 'Defender', club: 'Palmeiras', marketValueM: 2 },
    { name: 'Junior Alonso', position: 'Defender', club: 'Boca Juniors', marketValueM: 2 },
    { name: 'Andrés Cubas', position: 'Midfielder', club: 'Vancouver Whitecaps', marketValueM: 3 },
    { name: 'Damián Bobadilla', position: 'Midfielder', club: 'São Paulo', marketValueM: 3 },
    { name: 'Miguel Almirón', position: 'Forward', club: 'Atlanta United', marketValueM: 3 },
    { name: 'Antonio Sanabria', position: 'Forward', club: 'Cremonese', marketValueM: 3 },
  ],
  CHI: [
    { name: 'Brayan Cortés', position: 'Goalkeeper', club: 'Peñarol', marketValueM: 1 },
    { name: 'Gary Medel', position: 'Defender', club: 'Boca Juniors', marketValueM: 2 },
    { name: 'Guillermo Maripán', position: 'Defender', club: 'Torino', marketValueM: 2 },
    { name: 'Arturo Vidal', position: 'Midfielder', club: 'Colo-Colo', marketValueM: 3 },
    { name: 'Charles Aránguiz', position: 'Midfielder', club: 'Internacional', marketValueM: 3 },
    { name: 'Alexis Sánchez', position: 'Forward', club: 'Udinese', marketValueM: 3 },
    { name: 'Eduardo Vargas', position: 'Forward', club: 'Atlético Mineiro', marketValueM: 3 },
  ],
  VEN: [
    { name: 'Rafael Romo', position: 'Goalkeeper', club: 'Vitória', marketValueM: 1 },
    { name: 'Yordan Osorio', position: 'Defender', club: 'Parma', marketValueM: 2 },
    { name: 'Jhon Chancellor', position: 'Defender', club: 'Sydney FC', marketValueM: 2 },
    { name: 'Yangel Herrera', position: 'Midfielder', club: 'Girona', marketValueM: 3 },
    { name: 'Eduard Bello', position: 'Forward', club: 'Liga de Quito', marketValueM: 3 },
    { name: 'Salomón Rondón', position: 'Forward', club: 'Pachuca', marketValueM: 3 },
  ],
  BOL: [
    { name: 'Carlos Lampe', position: 'Goalkeeper', club: 'Always Ready', marketValueM: 1 },
    { name: 'Diego Medina', position: 'Defender', club: 'San Antonio Bulo Bulo', marketValueM: 2 },
    { name: 'Robson Matheus', position: 'Midfielder', club: 'Bolívar', marketValueM: 3 },
    { name: 'Marcelo Moreno', position: 'Forward', club: 'Cerro Porteño', marketValueM: 3 },
  ],
  PER: [
    { name: 'Pedro Gallese', position: 'Goalkeeper', club: 'Orlando City', marketValueM: 1 },
    { name: 'Renato Tapia', position: 'Midfielder', club: 'Leganés', marketValueM: 3 },
    { name: 'Yoshimar Yotún', position: 'Midfielder', club: 'Sporting Cristal', marketValueM: 3 },
    { name: 'Christian Cueva', position: 'Midfielder', club: 'Cienciano', marketValueM: 3 },
    { name: 'Gianluca Lapadula', position: 'Forward', club: 'Cagliari', marketValueM: 3 },
    { name: 'Paolo Guerrero', position: 'Forward', club: 'Alianza Lima', marketValueM: 3 },
  ],
  MAR: [
    { name: 'Yassine Bounou', position: 'Goalkeeper', club: 'Al-Hilal', marketValueM: 2 },
    { name: 'Achraf Hakimi', position: 'Defender', club: 'Paris Saint-Germain', marketValueM: 19 },
    { name: 'Nayef Aguerd', position: 'Defender', club: 'Real Sociedad', marketValueM: 8 },
    { name: 'Romain Saïss', position: 'Defender', club: 'Al-Shabab', marketValueM: 3 },
    { name: 'Sofyan Amrabat', position: 'Midfielder', club: 'Real Betis', marketValueM: 9 },
    { name: 'Azzedine Ounahi', position: 'Midfielder', club: 'Marseille', marketValueM: 9 },
    { name: 'Brahim Díaz', position: 'Forward', club: 'Real Madrid', marketValueM: 25 },
    { name: 'Hakim Ziyech', position: 'Forward', club: 'Al-Duhail', marketValueM: 4 },
    { name: 'Youssef En-Nesyri', position: 'Forward', club: 'Fenerbahçe', marketValueM: 10 },
  ],
  TUN: [
    { name: 'Aymen Dahmen', position: 'Goalkeeper', club: 'CS Sfaxien', marketValueM: 1 },
    { name: 'Yassine Meriah', position: 'Defender', club: 'Esteghlal', marketValueM: 2 },
    { name: 'Ali Abdi', position: 'Defender', club: 'Caen', marketValueM: 2 },
    { name: 'Aïssa Laidouni', position: 'Midfielder', club: 'Hellas Verona', marketValueM: 9 },
    { name: 'Ferjani Sassi', position: 'Midfielder', club: 'Al-Duhail', marketValueM: 4 },
    { name: 'Wahbi Khazri', position: 'Forward', club: 'Montpellier', marketValueM: 3 },
    { name: 'Issam Jebali', position: 'Forward', club: 'Odense', marketValueM: 3 },
  ],
  EGY: [
    { name: 'Mohamed El-Shenawy', position: 'Goalkeeper', club: 'Al-Ahly', marketValueM: 1 },
    { name: 'Mohamed Hany', position: 'Defender', club: 'Al-Ahly', marketValueM: 2 },
    { name: 'Mohamed Hamdy', position: 'Defender', club: 'Pyramids', marketValueM: 2 },
    { name: 'Mohamed Elneny', position: 'Midfielder', club: 'Al-Jazira', marketValueM: 3 },
    { name: 'Mostafa Mohamed', position: 'Forward', club: 'Nantes', marketValueM: 3 },
    { name: 'Trezeguet', position: 'Forward', club: 'Trabzonspor', marketValueM: 4 },
    { name: 'Mohamed Salah', position: 'Forward', club: 'Liverpool', marketValueM: 25 },
  ],
  ALG: [
    { name: 'Raïs M’Bolhi', position: 'Goalkeeper', club: 'CR Belouizdad', marketValueM: 1 },
    { name: 'Aïssa Mandi', position: 'Defender', club: 'Lille', marketValueM: 8 },
    { name: 'Ramy Bensebaini', position: 'Defender', club: 'Borussia Dortmund', marketValueM: 19 },
    { name: 'Ismaël Bennacer', position: 'Midfielder', club: 'Marseille', marketValueM: 9 },
    { name: 'Houssem Aouar', position: 'Midfielder', club: 'Al-Ittihad', marketValueM: 4 },
    { name: 'Riyad Mahrez', position: 'Forward', club: 'Al-Ahli', marketValueM: 4 },
    { name: 'Islam Slimani', position: 'Forward', club: 'Skopje', marketValueM: 3 },
    { name: 'Saïd Benrahma', position: 'Forward', club: 'Lyon', marketValueM: 10 },
  ],
  SEN: [
    { name: 'Édouard Mendy', position: 'Goalkeeper', club: 'Al-Ahli', marketValueM: 2 },
    { name: 'Kalidou Koulibaly', position: 'Defender', club: 'Al-Hilal', marketValueM: 3 },
    { name: 'Abdou Diallo', position: 'Defender', club: 'Al-Arabi', marketValueM: 3 },
    { name: 'Idrissa Gueye', position: 'Midfielder', club: 'Everton', marketValueM: 9 },
    { name: 'Pape Matar Sarr', position: 'Midfielder', club: 'Tottenham', marketValueM: 22 },
    { name: 'Sadio Mané', position: 'Forward', club: 'Al-Nassr', marketValueM: 4 },
    { name: 'Ismaïla Sarr', position: 'Forward', club: 'Crystal Palace', marketValueM: 10 },
    { name: 'Nicolas Jackson', position: 'Forward', club: 'Bayern Munich', marketValueM: 25 },
  ],
  NGA: [
    { name: 'Stanley Nwabali', position: 'Goalkeeper', club: 'Chippa United', marketValueM: 1 },
    { name: 'William Troost-Ekong', position: 'Defender', club: 'Al-Kholood', marketValueM: 3 },
    { name: 'Calvin Bassey', position: 'Defender', club: 'Fulham', marketValueM: 8 },
    { name: 'Ola Aina', position: 'Defender', club: 'Nottingham Forest', marketValueM: 8 },
    { name: 'Wilfred Ndidi', position: 'Midfielder', club: 'Besiktas', marketValueM: 3 },
    { name: 'Frank Onyeka', position: 'Midfielder', club: 'Augsburg', marketValueM: 9 },
    { name: 'Alex Iwobi', position: 'Midfielder', club: 'Fulham', marketValueM: 9 },
    { name: 'Victor Osimhen', position: 'Forward', club: 'Galatasaray', marketValueM: 10 },
    { name: 'Ademola Lookman', position: 'Forward', club: 'Atalanta', marketValueM: 25 },
    { name: 'Samuel Chukwueze', position: 'Forward', club: 'Milan', marketValueM: 25 },
  ],
  GHA: [
    { name: 'Lawrence Ati-Zigi', position: 'Goalkeeper', club: 'St. Gallen', marketValueM: 1 },
    { name: 'Jonathan Mensah', position: 'Defender', club: 'San Jose Earthquakes', marketValueM: 2 },
    { name: 'Alexander Djiku', position: 'Defender', club: 'Fenerbahçe', marketValueM: 8 },
    { name: 'Thomas Partey', position: 'Midfielder', club: 'Villarreal', marketValueM: 9 },
    { name: 'Mohammed Kudus', position: 'Midfielder', club: 'Tottenham', marketValueM: 22 },
    { name: 'Jordan Ayew', position: 'Forward', club: 'Leicester City', marketValueM: 10 },
    { name: 'Iñaki Williams', position: 'Forward', club: 'Athletic Bilbao', marketValueM: 10 },
    { name: 'Antoine Semenyo', position: 'Forward', club: 'Bournemouth', marketValueM: 10 },
  ],
  CMR: [
    { name: 'André Onana', position: 'Goalkeeper', club: 'Manchester United', marketValueM: 11 },
    { name: 'Jean-Charles Castelletto', position: 'Defender', club: 'Nantes', marketValueM: 2 },
    { name: 'Christopher Wooh', position: 'Defender', club: 'Rennes', marketValueM: 8 },
    { name: 'Pierre Kunde', position: 'Midfielder', club: 'Mainz', marketValueM: 9 },
    { name: 'Frank Anguissa', position: 'Midfielder', club: 'Napoli', marketValueM: 22 },
    { name: 'Bryan Mbeumo', position: 'Forward', club: 'Manchester United', marketValueM: 25 },
    { name: 'Karl Toko Ekambi', position: 'Forward', club: 'Abha', marketValueM: 3 },
    { name: 'Vincent Aboubakar', position: 'Forward', club: 'Hatayspor', marketValueM: 4 },
  ],
  CIV: [
    { name: 'Yahia Fofana', position: 'Goalkeeper', club: 'Angers', marketValueM: 1 },
    { name: 'Serge Aurier', position: 'Defender', club: 'Galatasaray', marketValueM: 8 },
    { name: 'Willy Boly', position: 'Defender', club: 'Nottingham Forest', marketValueM: 8 },
    { name: 'Eric Bailly', position: 'Defender', club: 'Sky Blue', marketValueM: 2 },
    { name: 'Franck Kessié', position: 'Midfielder', club: 'Al-Ahli', marketValueM: 4 },
    { name: 'Ibrahim Sangaré', position: 'Midfielder', club: 'Nottingham Forest', marketValueM: 9 },
    { name: 'Sébastien Haller', position: 'Forward', club: 'Borussia Dortmund', marketValueM: 25 },
    { name: 'Simon Adingra', position: 'Forward', club: 'Sunderland', marketValueM: 10 },
    { name: 'Nicolas Pépé', position: 'Forward', club: 'Villarreal', marketValueM: 10 },
  ],
  COD: [
    { name: 'Lionel Mpasi', position: 'Goalkeeper', club: 'Rodez', marketValueM: 1 },
    { name: 'Chancel Mbemba', position: 'Defender', club: 'Lille', marketValueM: 8 },
    { name: 'Arthur Masuaku', position: 'Defender', club: 'Beşiktaş', marketValueM: 8 },
    { name: 'Aaron Wan-Bissaka', position: 'Defender', club: 'West Ham', marketValueM: 8 },
    { name: 'Samuel Moutoussamy', position: 'Midfielder', club: 'Nantes', marketValueM: 3 },
    { name: 'Yoane Wissa', position: 'Forward', club: 'Newcastle United', marketValueM: 25 },
    { name: 'Cédric Bakambu', position: 'Forward', club: 'Real Betis', marketValueM: 10 },
    { name: 'Fiston Mayele', position: 'Forward', club: 'Pyramids', marketValueM: 3 },
  ],
  RSA: [
    { name: 'Ronwen Williams', position: 'Goalkeeper', club: 'Mamelodi Sundowns', marketValueM: 1 },
    { name: 'Siyanda Xulu', position: 'Defender', club: 'Sekhukhune United', marketValueM: 2 },
    { name: 'Khuliso Mudau', position: 'Defender', club: 'Mamelodi Sundowns', marketValueM: 2 },
    { name: 'Teboho Mokoena', position: 'Midfielder', club: 'Mamelodi Sundowns', marketValueM: 3 },
    { name: 'Themba Zwane', position: 'Midfielder', club: 'Mamelodi Sundowns', marketValueM: 3 },
    { name: 'Lyle Foster', position: 'Forward', club: 'Burnley', marketValueM: 10 },
    { name: 'Percy Tau', position: 'Forward', club: 'Qatar SC', marketValueM: 3 },
  ],
  CPV: [
    { name: 'Vozinha', position: 'Goalkeeper', club: 'Casa Pia', marketValueM: 1 },
    { name: 'Roberto Lopes', position: 'Defender', club: 'Shamrock Rovers', marketValueM: 2 },
    { name: 'Logan Costa', position: 'Defender', club: 'Toulouse', marketValueM: 2 },
    { name: 'Ryan Mendes', position: 'Forward', club: 'NorthEast United', marketValueM: 3 },
    { name: 'Garry Rodrigues', position: 'Forward', club: 'Bali United', marketValueM: 3 },
    { name: 'Júlio Tavares', position: 'Forward', club: 'Westerlo', marketValueM: 3 },
  ],
  BIH: [
    { name: 'Nikola Vasilj', position: 'Goalkeeper', club: 'Hamburger SV', marketValueM: 1 },
    { name: 'Sead Kolašinac', position: 'Defender', club: 'Atalanta', marketValueM: 19 },
    { name: 'Anel Ahmedhodžić', position: 'Defender', club: 'Sheffield United', marketValueM: 8 },
    { name: 'Miralem Pjanić', position: 'Midfielder', club: 'CSKA Moscow', marketValueM: 3 },
    { name: 'Edin Džeko', position: 'Forward', club: 'Fenerbahçe', marketValueM: 10 },
    { name: 'Ermedin Demirović', position: 'Forward', club: 'VfB Stuttgart', marketValueM: 10 },
  ],
  NZL: [
    { name: 'Oliver Sail', position: 'Goalkeeper', club: 'Western Sydney Wanderers', marketValueM: 1 },
    { name: 'Tim Payne', position: 'Defender', club: 'Auckland FC', marketValueM: 2 },
    { name: 'Michael Boxall', position: 'Defender', club: 'Minnesota United', marketValueM: 2 },
    { name: 'Marko Stamenić', position: 'Midfielder', club: 'Olympiacos', marketValueM: 3 },
    { name: 'Liberato Cacace', position: 'Defender', club: 'Wellington Phoenix', marketValueM: 2 },
    { name: 'Chris Wood', position: 'Forward', club: 'Nottingham Forest', marketValueM: 10 },
    { name: 'Kosta Barbarouses', position: 'Forward', club: 'Auckland FC', marketValueM: 3 },
  ],
}

export function getFallbackSquad(fifaCode: string) {
  return WC_FALLBACK_SQUADS[fifaCode.toUpperCase()] ?? null
}

// Platta ut alla spelare till en lista med {name, country}.
// Används som autocomplete-dropdown för "Skytteligavinnare"-bonustippet.
// Ersätts automatiskt med riktiga trupper när football-data.org levererar dem.
export interface FallbackPlayerWithCountry extends FallbackPlayer {
  country: string // FIFA-koden
}

export function getAllFallbackPlayers(): FallbackPlayerWithCountry[] {
  const out: FallbackPlayerWithCountry[] = []
  for (const [code, players] of Object.entries(WC_FALLBACK_SQUADS)) {
    for (const p of players) {
      out.push({ ...p, country: code })
    }
  }
  return out
}
